### ISSUE TITLE
1.12.2无法启动客户端

### ISSUE THREAD

**Issue by 200542053** [MakesYT/chatsync_mods_forge#2]
装了mixinbooter时，提示缺少".minecraft\get_clipboard_image.dll: Can't find dependent libraries"
[crash-2023-05-01_16.14.31-client.txt](https://github.com/MakesYT/chatsync_mods_forge/files/11364320/crash-2023-05-01_16.14.31-client.txt)

什么都没装时直接无法启动
[latest.log](https://github.com/MakesYT/chatsync_mods_forge/files/11364322/latest.log)

Minecraft：1.12.2
Forge：14.23.5.2860

**Comment by Maklith** [comment]
mod啥版本的？有两个跨版本错误我没有更正版本号

**Comment by Maklith** [comment]
在最新(dc35459)的构建无法复现此问题
尝试
1. 检查E:\MultiMC\instances\新测试1.12.2\.minecraft\get_clipboard_image.dll此文件是否存在
2. 更换Java,尝试官方或IBM构建 
3. 尝试使用_MixinBootstrap-1.1.0

**Comment by Maklith** [comment]
很抱歉已确认在1.12.2的构建中的dll存在问题,已在1.4.1-2版本修复,补充说明:需要手动删除get_clipboard_image.dll文件,否则更新可能无效
