### ISSUE TITLE
1.12.2客户端无法启动

### ISSUE THREAD

**Issue by 1zyao** [MakesYT/chatsync_mods_forge#3]
安装mixinbooter启动时报错Caused by: java.lang.UnsatisfiedLinkError: H:\RETE1.12.2\.minecraft\get_clipboard_image.dll: Can't find dependent libraries
[crash-2023-05-03_17.08.49-client.txt](https://github.com/MakesYT/chatsync_mods_forge/files/11381069/crash-2023-05-03_17.08.49-client.txt)
 forge：14.23.5.2860 
mod版本：1.12.2-1.4.1-1

**Comment by Maklith** [comment]
尝试一下 #2 中的方法

**Comment by Maklith** [comment]
很抱歉已确认在1.12.2的构建中的dll存在问题,已在1.4.1-2版本修复,补充说明:需要手动删除get_clipboard_image.dll文件,否则更新可能无效
